name: auto_tag

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - master

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to test versioning
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Autotag
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
